# Generated by Django 5.0 on 2023-12-07 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieorder',
            old_name='movie',
            new_name='movie_order',
        ),
        migrations.RenameField(
            model_name='movieorder',
            old_name='user',
            new_name='user_order',
        ),
    ]
